### ISSUE TITLE
Can not validate addresses

### ISSUE THREAD

**Issue by thedodd** [taxjar/taxjar-go#11]
Hello TaxJar folks. I am running into an issue where I am attempting to validate an address via the Go SDK. I am using the `*taxjar.Config.ValidateAddress(taxjar.ValidateAddressParams{...})` method, and I am getting the following error:

```
0 Not Found - No such route 'POST /v2/addresses/validate'
```

A few pertinent details:
- this is on the sandbox API.
- using v1.1.0 of the Go client.
- the input to the call is a completely valid address, using alpha-2 codes for country and state (it is a US address).
- the associated TaxJar plan is a Professional level plan.

**Comment by tiffanie-taxjar** [comment]
Hi @thedodd - sorry for the delayed response here!

I am sorry it's a bit buried, but it is noted in our documentation [here](https://developers.taxjar.com/api/reference/#sandbox-environment), "Some of the production API endpoints are not fully supported in the sandbox environment." If you click on the link in that sentence it will lead you to [this support article](https://support.taxjar.com/article/677-which-sandbox-endpoints-are-currently-supported) that details the supported endpoints for our sandbox. Unfortunately address validation is not one of the supported endpoints. 

However, there is good news, the address validation endpoint is not counted towards the billable API calls. You can test address validation using your production token for free! 

I hope that helps, please let us know if you have any more questions or encounter any other issues!

**Comment by thedodd** [comment]
Thanks for the info @tiffanie-taxjar! Good to know.
