### ISSUE TITLE
OrderLineItem is json.Number but the API specifies string

### ISSUE THREAD

**Issue by calvinosg** [taxjar/taxjar-go#16]
Updating to the latest version of taxjar go broke our existing integration with this commit: https://github.com/taxjar/taxjar-go/commit/04f3fd07bffe662c3e1c70c6f6f8b377ce5e4021

The line item IDs are strings per the TaxJar Documentation:

<img width="586" alt="Screenshot 2022-09-07 at 10 21 56" src="https://user-images.githubusercontent.com/113015814/188828415-74ed2ae2-c0cb-4762-96f1-3762224b85a9.png">

We currently use UUIDs for our line items and so switching to json.Number would not be an insignificant refactor with our integration, as well as not being per the API documentation.

**Comment by andrewbohm** [comment]
We are having the same problem as well. Go the struct is json.Number... yet ID should be string per the documentation.

**Comment by andrewbohm** [comment]
> Updating to the latest version of taxjar go broke our existing integration with this commit: [04f3fd0](https://github.com/taxjar/taxjar-go/commit/04f3fd07bffe662c3e1c70c6f6f8b377ce5e4021)
> 
> The line item IDs are strings per the TaxJar Documentation:
> 
> <img alt="Screenshot 2022-09-07 at 10 21 56" width="586" src="https://user-images.githubusercontent.com/113015814/188828415-74ed2ae2-c0cb-4762-96f1-3762224b85a9.png">
> 
> We currently use UUIDs for our line items and so switching to json.Number would not be an insignificant refactor with our integration, as well as not being per the API documentation.

@calvinosg did you decide a work around?

**Comment by calvinosg** [comment]
@andrewbohm unfortunately not, we just reverted to an older version until this bug is fixed.
